# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 480)
        self.listView = QtWidgets.QListView(Dialog)
        self.listView.setGeometry(QtCore.QRect(435, 30, 201, 361))
        self.listView.setObjectName("listView")
        self.sendText = QtWidgets.QPlainTextEdit(Dialog)
        self.sendText.setGeometry(QtCore.QRect(0, 400, 431, 71))
        self.sendText.setObjectName("sendText")
        self.SendButton = QtWidgets.QPushButton(Dialog)
        self.SendButton.setGeometry(QtCore.QRect(434, 400, 81, 71))
        self.SendButton.setObjectName("SendButton")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(0, 30, 431, 361))
        self.textBrowser.setObjectName("textBrowser")
        self.ipText = QtWidgets.QLineEdit(Dialog)
        self.ipText.setGeometry(QtCore.QRect(80, 0, 191, 21))
        self.ipText.setObjectName("ipText")
        self.label1 = QtWidgets.QLabel(Dialog)
        self.label1.setGeometry(QtCore.QRect(20, 0, 61, 21))
        self.label1.setObjectName("label1")
        self.findipButton = QtWidgets.QPushButton(Dialog)
        self.findipButton.setGeometry(QtCore.QRect(280, 0, 75, 21))
        self.findipButton.setObjectName("findipButton")
        self.connectButton = QtWidgets.QPushButton(Dialog)
        self.connectButton.setGeometry(QtCore.QRect(360, 0, 75, 21))
        self.connectButton.setObjectName("connectButton")
        self.label2 = QtWidgets.QLabel(Dialog)
        self.label2.setGeometry(QtCore.QRect(450, 0, 71, 21))
        self.label2.setObjectName("label2")
        self.labelconnect = QtWidgets.QLabel(Dialog)
        self.labelconnect.setGeometry(QtCore.QRect(520, 0, 71, 21))
        self.labelconnect.setStyleSheet("color: rgb(255, 0, 0);")
        self.labelconnect.setTextFormat(QtCore.Qt.AutoText)
        self.labelconnect.setScaledContents(False)
        self.labelconnect.setObjectName("labelconnect")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "TalkRoom"))
        self.SendButton.setText(_translate("Dialog", "发送消息"))
        self.label1.setText(_translate("Dialog", "服务器IP:"))
        self.findipButton.setText(_translate("Dialog", "自动寻找"))
        self.connectButton.setText(_translate("Dialog", "连接"))
        self.label2.setText(_translate("Dialog", "服务器状态："))
        self.labelconnect.setText(_translate("Dialog", "未连接"))
